import type { Metadata } from "next";
import "./globals.css";
// // import Header from "@/components/Header";
// import Footer from "@/components/Footer";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { CssBaseline } from "@mui/material";
import ThemeProvider from "./theme-provider";

export const metadata: Metadata = {
  title: "DigiSus-project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <ThemeProvider>
          <CssBaseline />
          <AppRouterCacheProvider>
            {/* <Header /> */}
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                flexGrow: 1,
              }}
            >
              {children}
            </div>
            {/* <Footer /> */}
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
